/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Models\;

/**
 * Resource
 *
 * Auto-generated Laravel Resource for  operation (HTTP )
 *
 * OpenAPI Operation: 
 * Response:  
 * Schema: 
 */
class Resource extends JsonResource
{
    /**
     * HTTP status code - Hardcoded: 
     */
    protected int $httpCode = ;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        /** @var  $model */
        $model = $this->resource;

        return [
        ];
    }

    /**
     * Customize the outgoing response.
     *
     * Enforces HTTP  status code
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response  $response
     * @return void
     */
    public function withResponse($request, $response)
    {
        // Set hardcoded HTTP  status
        $response->setStatusCode($this->httpCode);

    }
}
