/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Api;

use App\Models.NotFoundError;
use App\Models.Status;
use App\Http\Resources\GetBoard200Resource|404Resource;

/**
 * TicTacApiApi
 *
 * Handler interface - implement this to provide business logic
 * Returns Resources with compile-time type safety via union types
 *
 * Operation: getBoard
 */
interface TicTacApiApi
{
    /**
     * Get the game board
     *
     * Retrieves the current state of the board and the winner.
     *
     * @param string $game_id Unique game identifier
     * @return GetBoard200Resource|404Resource
     */
    public function getBoard(
        string $game_id
    ): GetBoard200Resource|404Resource;

}
