/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Api;

use App\Models.BadRequestError;
use App\Models.Error;
use App\Models.Game;
use App\Models.MoveHistory;
use App\Models.MoveRequest;
use App\Models.NotFoundError;
use App\Models.SquareResponse;
use App\Models.Status;
use App\Http\Resources\GetBoard200Resource|404Resource;
use App\Http\Resources\GetGame200Resource|404Resource;
use App\Http\Resources\GetMoves200Resource|404Resource;
use App\Http\Resources\GetSquare200Resource|400Resource|404Resource;
use App\Http\Resources\PutSquare200Resource|400Resource|404Resource|409Resource;

/**
 * GameplayApiApi
 *
 * Handler interface - implement this to provide business logic
 * Returns Resources with compile-time type safety via union types
 *
 * Operation: getBoard
 * Operation: getGame
 * Operation: getMoves
 * Operation: getSquare
 * Operation: putSquare
 */
interface GameplayApiApi
{
    /**
     * Get the game board
     *
     * Retrieves the current state of the board and the winner.
     *
     * @param string $game_id Unique game identifier
     * @return GetBoard200Resource|404Resource
     */
    public function getBoard(
        string $game_id
    ): GetBoard200Resource|404Resource;

    /**
     * Get game details
     *
     * Retrieves detailed information about a specific game.
     *
     * @param string $game_id Unique game identifier
     * @return GetGame200Resource|404Resource
     */
    public function getGame(
        string $game_id
    ): GetGame200Resource|404Resource;

    /**
     * Get move history
     *
     * Retrieves the complete move history for a game.
     *
     * @param string $game_id Unique game identifier
     * @return GetMoves200Resource|404Resource
     */
    public function getMoves(
        string $game_id
    ): GetMoves200Resource|404Resource;

    /**
     * Get a single board square
     *
     * Retrieves the requested square.
     *
     * @param string $game_id Unique game identifier
     * @param int $row Board row (vertical coordinate)
     * @param int $column Board column (horizontal coordinate)
     * @return GetSquare200Resource|400Resource|404Resource
     */
    public function getSquare(
        string $game_id,
        int $row,
        int $column
    ): GetSquare200Resource|400Resource|404Resource;

    /**
     * Set a single board square
     *
     * Places a mark on the board and retrieves the whole board and the winner (if any).
     *
     * @param string $game_id Unique game identifier
     * @param int $row Board row (vertical coordinate)
     * @param int $column Board column (horizontal coordinate)
     * @param \App\Models\MoveRequest $move_request 
     * @return PutSquare200Resource|400Resource|404Resource|409Resource
     */
    public function putSquare(
        string $game_id,
        int $row,
        int $column,
        \App\Models\MoveRequest $move_request
    ): PutSquare200Resource|400Resource|404Resource|409Resource;

}
