/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Move DTO
 *
 * Auto-generated from OpenAPI schema: move
 * 
 */
class Move
{
    /**
     * Sequential move number
     */
    public int $move_number;
    /**
     * Player who made the move
     */
    public string $player_id;
    public string $mark;
    /**
     * Board coordinate (1-3)
     */
    public int $row;
    /**
     * Board coordinate (1-3)
     */
    public int $column;
    /**
     * When the move was made
     */
    public \DateTime $timestamp;

    /**
     * Constructor
     */
    public function __construct(
        int $move_number,
        string $player_id,
        string $mark,
        int $row,
        int $column,
        \DateTime $timestamp,
    ) {
        $this->move_number = $move_number;
        $this->player_id = $player_id;
        $this->mark = $mark;
        $this->row = $row;
        $this->column = $column;
        $this->timestamp = $timestamp;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            move_number: $data['moveNumber'],
            player_id: $data['playerId'],
            mark: $data['mark'],
            row: $data['row'],
            column: $data['column'],
            timestamp: $data['timestamp'],
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'moveNumber' => $this->move_number,
            'playerId' => $this->player_id,
            'mark' => $this->mark,
            'row' => $this->row,
            'column' => $this->column,
            'timestamp' => $this->timestamp,
        ];
    }
}
