/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * ValidationErrorAllOfErrors DTO
 *
 * Auto-generated from OpenAPI schema: validationError_allOf_errors
 * 
 */
class ValidationErrorAllOfErrors
{
    /**
     * Field that failed validation
     */
    public string $field;
    /**
     * Validation error message
     */
    public string $message;
    public ?mixed $value = null;

    /**
     * Constructor
     */
    public function __construct(
        string $field,
        string $message,
        ?mixed $value = null,
    ) {
        $this->field = $field;
        $this->message = $message;
        $this->value = $value;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            field: $data['field'],
            message: $data['message'],
            value: $data['value'] ?? null,
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'field' => $this->field,
            'message' => $this->message,
            'value' => $this->value,
        ];
    }
}
