/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * CreateGameFormRequest
 *
 * Auto-generated FormRequest for createGame operation
 * Validation rules extracted from OpenAPI schema
 */
class CreateGameFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;  // Authorization logic should be implemented in middleware
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'mode' => ['required'],
            'opponentId' => ['sometimes', 'string', 'uuid'],
            'isPrivate' => ['sometimes', 'boolean'],
            'metadata' => ['sometimes'],
        ];
    }
}
