/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Game DTO
 *
 * Auto-generated from OpenAPI schema: game
 * 
 */
class Game
{
    /**
     * Unique game identifier
     */
    public string $id;
    public \App\Models\GameStatus $status;
    public \App\Models\GameMode $mode;
    /**
     * Player assigned to X marks
     */
    public \App\Models\Player $player_x = null;
    /**
     * Player assigned to O marks
     */
    public \App\Models\Player $player_o = null;
    public \App\Models\Mark $current_turn = null;
    public \App\Models\Winner $winner = null;
    /**
     * 3x3 game board represented as nested arrays
     */
    public \App\Models\Mark[][] $board;
    /**
     * Game creation timestamp
     */
    public \DateTime $created_at;
    /**
     * Last update timestamp
     */
    public \DateTime $updated_at = null;
    /**
     * Game completion timestamp
     */
    public \DateTime $completed_at = null;

    /**
     * Constructor
     */
    public function __construct(
        string $id,
        \App\Models\GameStatus $status,
        \App\Models\GameMode $mode,
        \App\Models\Player $player_x = null,
        \App\Models\Player $player_o = null,
        \App\Models\Mark $current_turn = null,
        \App\Models\Winner $winner = null,
        \App\Models\Mark[][] $board,
        \DateTime $created_at,
        \DateTime $updated_at = null,
        \DateTime $completed_at = null,
    ) {
        $this->id = $id;
        $this->status = $status;
        $this->mode = $mode;
        $this->player_x = $player_x;
        $this->player_o = $player_o;
        $this->current_turn = $current_turn;
        $this->winner = $winner;
        $this->board = $board;
        $this->created_at = $created_at;
        $this->updated_at = $updated_at;
        $this->completed_at = $completed_at;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            status: $data['status'],
            mode: $data['mode'],
            player_x: $data['playerX'] ?? null,
            player_o: $data['playerO'] ?? null,
            current_turn: $data['currentTurn'] ?? null,
            winner: $data['winner'] ?? null,
            board: $data['board'],
            created_at: $data['createdAt'],
            updated_at: $data['updatedAt'] ?? null,
            completed_at: $data['completedAt'] ?? null,
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'status' => $this->status,
            'mode' => $this->mode,
            'playerX' => $this->player_x,
            'playerO' => $this->player_o,
            'currentTurn' => $this->current_turn,
            'winner' => $this->winner,
            'board' => $this->board,
            'createdAt' => $this->created_at,
            'updatedAt' => $this->updated_at,
            'completedAt' => $this->completed_at,
        ];
    }
}
