/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * GameListResponse DTO
 *
 * Auto-generated from OpenAPI schema: gameListResponse
 * 
 */
class GameListResponse
{
    public \App\Models\Game[] $games;
    public \App\Models\Pagination $pagination;

    /**
     * Constructor
     */
    public function __construct(
        \App\Models\Game[] $games,
        \App\Models\Pagination $pagination,
    ) {
        $this->games = $games;
        $this->pagination = $pagination;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            games: $data['games'],
            pagination: $data['pagination'],
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'games' => $this->games,
            'pagination' => $this->pagination,
        ];
    }
}
