/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Player DTO
 *
 * Auto-generated from OpenAPI schema: player
 * 
 */
class Player
{
    /**
     * Unique player identifier
     */
    public string $id;
    /**
     * Player username
     */
    public string $username;
    /**
     * Player display name
     */
    public string $display_name = null;
    /**
     * URL to player avatar image
     */
    public string $avatar_url = null;

    /**
     * Constructor
     */
    public function __construct(
        string $id,
        string $username,
        string $display_name = null,
        string $avatar_url = null,
    ) {
        $this->id = $id;
        $this->username = $username;
        $this->display_name = $display_name;
        $this->avatar_url = $avatar_url;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            username: $data['username'],
            display_name: $data['displayName'] ?? null,
            avatar_url: $data['avatarUrl'] ?? null,
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'username' => $this->username,
            'displayName' => $this->display_name,
            'avatarUrl' => $this->avatar_url,
        ];
    }
}
