/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * SquareResponse DTO
 *
 * Auto-generated from OpenAPI schema: squareResponse
 * 
 */
class SquareResponse
{
    /**
     * Board coordinate (1-3)
     */
    public int $row;
    /**
     * Board coordinate (1-3)
     */
    public int $column;
    public \App\Models\Mark $mark;

    /**
     * Constructor
     */
    public function __construct(
        int $row,
        int $column,
        \App\Models\Mark $mark,
    ) {
        $this->row = $row;
        $this->column = $column;
        $this->mark = $mark;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            row: $data['row'],
            column: $data['column'],
            mark: $data['mark'],
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'row' => $this->row,
            'column' => $this->column,
            'mark' => $this->mark,
        ];
    }
}
