/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Status DTO
 *
 * Auto-generated from OpenAPI schema: status
 * 
 * Current game status including board state and winner
 * 
 */
class Status
{
    public \App\Models\Winner $winner;
    /**
     * 3x3 game board represented as nested arrays
     */
    public \App\Models\Mark[][] $board;

    /**
     * Constructor
     */
    public function __construct(
        \App\Models\Winner $winner,
        \App\Models\Mark[][] $board,
    ) {
        $this->winner = $winner;
        $this->board = $board;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            winner: $data['winner'],
            board: $data['board'],
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'winner' => $this->winner,
            'board' => $this->board,
        ];
    }
}
