/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Models;

/**
 * ValidationError DTO
 *
 * Auto-generated from OpenAPI schema: validationError
 * 
 */
class ValidationError
{
    /**
     * Error code
     */
    public string $code;
    /**
     * Human-readable error message
     */
    public string $message;
    /**
     * Additional error details
     */
    public array&lt;string,mixed&gt; $details = null;
    public \App\Models\ValidationErrorAllOfErrors[] $errors;

    /**
     * Constructor
     */
    public function __construct(
        string $code,
        string $message,
        array&lt;string,mixed&gt; $details = null,
        \App\Models\ValidationErrorAllOfErrors[] $errors,
    ) {
        $this->code = $code;
        $this->message = $message;
        $this->details = $details;
        $this->errors = $errors;
    }

    /**
     * Create from array
     *
     * @param array<string, mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self(
            code: $data['code'],
            message: $data['message'],
            details: $data['details'] ?? null,
            errors: $data['errors'],
        );
    }

    /**
     * Convert to array
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'code' => $this->code,
            'message' => $this->message,
            'details' => $this->details,
            'errors' => $this->errors,
        ];
    }
}
