/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Models\Game;

/**
 * CreateGame201Resource
 *
 * Auto-generated Laravel Resource for createGame operation (HTTP 201)
 *
 * OpenAPI Operation: createGame
 * Response: 201 Game created successfully
 * Schema: Game
 * Header: Location (REQUIRED)
 */
class CreateGame201Resource extends JsonResource
{
    /**
     * HTTP status code - Hardcoded: 201
     */
    protected int $httpCode = 201;

    /**
     * Location header (REQUIRED)
     */
    public ?string $location = null;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        /** @var Game $model */
        $model = $this->resource;

        return [
            'id' => $model->id,
            'status' => $model->status,
            'mode' => $model->mode,
            'playerX' => $model->player_x,
            'playerO' => $model->player_o,
            'currentTurn' => $model->current_turn,
            'winner' => $model->winner,
            'board' => $model->board,
            'createdAt' => $model->created_at,
            'updatedAt' => $model->updated_at,
            'completedAt' => $model->completed_at,
        ];
    }

    /**
     * Customize the outgoing response.
     *
     * Enforces HTTP 201 status code and headers
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response  $response
     * @return void
     */
    public function withResponse($request, $response)
    {
        // Set hardcoded HTTP 201 status
        $response->setStatusCode($this->httpCode);

        // Location header is REQUIRED
        if ($this->location === null) {
            throw new \RuntimeException(
                'Location header is REQUIRED for createGame (HTTP 201) but was not set'
            );
        }
        $response->header('Location', $this->location);

    }
}
