/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Models\MoveHistory;

/**
 * GetMoves200Resource
 *
 * Auto-generated Laravel Resource for getMoves operation (HTTP 200)
 *
 * OpenAPI Operation: getMoves
 * Response: 200 Successful response
 * Schema: MoveHistory
 */
class GetMoves200Resource extends JsonResource
{
    /**
     * HTTP status code - Hardcoded: 200
     */
    protected int $httpCode = 200;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        /** @var MoveHistory $model */
        $model = $this->resource;

        return [
            'gameId' => $model->game_id,
            'moves' => $model->moves,
        ];
    }

    /**
     * Customize the outgoing response.
     *
     * Enforces HTTP 200 status code
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response  $response
     * @return void
     */
    public function withResponse($request, $response)
    {
        // Set hardcoded HTTP 200 status
        $response->setStatusCode($this->httpCode);

    }
}
