/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Models\PlayerStats;

/**
 * GetPlayerStats200Resource
 *
 * Auto-generated Laravel Resource for getPlayerStats operation (HTTP 200)
 *
 * OpenAPI Operation: getPlayerStats
 * Response: 200 Successful response
 * Schema: PlayerStats
 */
class GetPlayerStats200Resource extends JsonResource
{
    /**
     * HTTP status code - Hardcoded: 200
     */
    protected int $httpCode = 200;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        /** @var PlayerStats $model */
        $model = $this->resource;

        return [
            'playerId' => $model->player_id,
            'player' => $model->player,
            'gamesPlayed' => $model->games_played,
            'wins' => $model->wins,
            'losses' => $model->losses,
            'draws' => $model->draws,
            'winRate' => $model->win_rate,
            'currentStreak' => $model->current_streak,
            'longestWinStreak' => $model->longest_win_streak,
        ];
    }

    /**
     * Customize the outgoing response.
     *
     * Enforces HTTP 200 status code
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response  $response
     * @return void
     */
    public function withResponse($request, $response)
    {
        // Set hardcoded HTTP 200 status
        $response->setStatusCode($this->httpCode);

    }
}
