/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Models\BadRequestError;

/**
 * ListGames400Resource
 *
 * Auto-generated Laravel Resource for listGames operation (HTTP 400)
 *
 * OpenAPI Operation: listGames
 * Response: 400 Bad Request - Invalid parameters
 * Schema: BadRequestError
 */
class ListGames400Resource extends JsonResource
{
    /**
     * HTTP status code - Hardcoded: 400
     */
    protected int $httpCode = 400;

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request): array
    {
        /** @var BadRequestError $model */
        $model = $this->resource;

        return [
            'code' => $model->code,
            'message' => $model->message,
            'details' => $model->details,
            'errorType' => $model->error_type,
        ];
    }

    /**
     * Customize the outgoing response.
     *
     * Enforces HTTP 400 status code
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response  $response
     * @return void
     */
    public function withResponse($request, $response)
    {
        // Set hardcoded HTTP 400 status
        $response->setStatusCode($this->httpCode);

    }
}
