/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

// DEBUG TEMPLATE - Testing what variables are available

// classname: Mark
// name: 
// description: 
// modelPackage: App\Models
// apiPackage: App

// Has vars? NO

// All vars:

namespace App\Models;

class Mark {
    // Testing...
}
