/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);  

namespace App\Http\Controllers;

use App\Api\GameManagementApiApi;
use App\Http\Requests\CreateGameFormRequest;
use App\Models\CreateGameRequest;
use Illuminate\Http\JsonResponse;

/**
 * CreateGameController
 *
 * Auto-generated controller for createGame operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: createGame
 * HTTP Method: POST /games
 */
class CreateGameController
{
    public function __construct(
        private readonly GameManagementApiApi $handler
    ) {}

    /**
     * Create a new game
     *
     * Creates a new TicTacToe game with specified configuration.
     *
     * @param \App\Models\CreateGameRequest $create_game_request
     * @return JsonResponse
     */
    public function __invoke(
        CreateGameFormRequest $request
    ): JsonResponse
    {
        // Convert validated data to DTO
        $dto = \App\Models\CreateGameRequest::fromArray($request->validated());

        // Delegate to Handler
        $resource = $this->handler->createGame(
            $dto
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
