/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);  

namespace App\Http\Controllers;

use App\Api\GameManagementApiApi;
use Illuminate\Http\JsonResponse;

/**
 * DeleteGameController
 *
 * Auto-generated controller for deleteGame operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: deleteGame
 * HTTP Method: DELETE /games/{gameId}
 */
class DeleteGameController
{
    public function __construct(
        private readonly GameManagementApiApi $handler
    ) {}

    /**
     * Delete a game
     *
     * Deletes a game. Only allowed for game creators or admins.
     *
     * @param string $game_id Unique game identifier
     * @return JsonResponse
     */
    public function __invoke(
        string $game_id
    ): JsonResponse
    {
        // Delegate to Handler
        $resource = $this->handler->deleteGame(
            $game_id
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
