/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);  

namespace App\Http\Controllers;

use App\Api\GameplayApiApi;
use Illuminate\Http\JsonResponse;

/**
 * GetMovesController
 *
 * Auto-generated controller for getMoves operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: getMoves
 * HTTP Method: GET /games/{gameId}/moves
 */
class GetMovesController
{
    public function __construct(
        private readonly GameplayApiApi $handler
    ) {}

    /**
     * Get move history
     *
     * Retrieves the complete move history for a game.
     *
     * @param string $game_id Unique game identifier
     * @return JsonResponse
     */
    public function __invoke(
        string $game_id
    ): JsonResponse
    {
        // Delegate to Handler
        $resource = $this->handler->getMoves(
            $game_id
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
