/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);  

namespace App\Http\Controllers;

use App\Api\GameManagementApiApi;
use Illuminate\Http\JsonResponse;

/**
 * ListGamesController
 *
 * Auto-generated controller for listGames operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: listGames
 * HTTP Method: GET /games
 */
class ListGamesController
{
    public function __construct(
        private readonly GameManagementApiApi $handler
    ) {}

    /**
     * List all games
     *
     * Retrieves a paginated list of games with optional filtering.
     *
     * @param int $page Page number for pagination
     * @param int $limit Number of items per page
     * @param \App\Models\GameStatus $status Filter by game status
     * @param string $player_id Filter games by player ID
     * @return JsonResponse
     */
    public function __invoke(
    ): JsonResponse
    {
        // Delegate to Handler
        $resource = $this->handler->listGames(
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
