/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 * API version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);  

namespace App\Http\Controllers;

use App\Api\GameplayApiApi;
use App\Http\Requests\PutSquareFormRequest;
use App\Models\MoveRequest;
use Illuminate\Http\JsonResponse;

/**
 * PutSquareController
 *
 * Auto-generated controller for putSquare operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: putSquare
 * HTTP Method: PUT /games/{gameId}/board/{row}/{column}
 */
class PutSquareController
{
    public function __construct(
        private readonly GameplayApiApi $handler
    ) {}

    /**
     * Set a single board square
     *
     * Places a mark on the board and retrieves the whole board and the winner (if any).
     *
     * @param string $game_id Unique game identifier
     * @param int $row Board row (vertical coordinate)
     * @param int $column Board column (horizontal coordinate)
     * @param \App\Models\MoveRequest $move_request
     * @return JsonResponse
     */
    public function __invoke(
        PutSquareFormRequest $request,
        string $game_id,
        int $row,
        int $column
    ): JsonResponse
    {
        // Convert validated data to DTO
        $dto = \App\Models\MoveRequest::fromArray($request->validated());

        // Delegate to Handler
        $resource = $this->handler->putSquare(
            $dto,
            $game_id,
            $row,
            $column
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
