/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Api;

use App\Models.BadRequestError;
use App\Models.CreateGameRequest;
use App\Models.ForbiddenError;
use App\Models.Game;
use App\Models.GameListResponse;
use App\Models.GameStatus;
use App\Models.NotFoundError;
use App\Models.UnauthorizedError;
use App\Models.ValidationError;
use App\Http\Resources\CreateGame201Resource|400Resource|401Resource|422Resource;
use App\Http\Resources\DeleteGame204Resource|403Resource|404Resource;
use App\Http\Resources\GetGame200Resource|404Resource;
use App\Http\Resources\ListGames200Resource|400Resource|401Resource;

/**
 * GameManagementApiApi
 *
 * Handler interface - implement this to provide business logic
 * Returns Resources with compile-time type safety via union types
 *
 * Operation: createGame
 * Operation: deleteGame
 * Operation: getGame
 * Operation: listGames
 */
interface GameManagementApiApi
{
    /**
     * Create a new game
     *
     * Creates a new TicTacToe game with specified configuration.
     *
     * @param \App\Models\CreateGameRequest $create_game_request 
     * @return CreateGame201Resource|400Resource|401Resource|422Resource
     */
    public function createGame(
        \App\Models\CreateGameRequest $create_game_request
    ): CreateGame201Resource|400Resource|401Resource|422Resource;

    /**
     * Delete a game
     *
     * Deletes a game. Only allowed for game creators or admins.
     *
     * @param string $game_id Unique game identifier
     * @return DeleteGame204Resource|403Resource|404Resource
     */
    public function deleteGame(
        string $game_id
    ): DeleteGame204Resource|403Resource|404Resource;

    /**
     * Get game details
     *
     * Retrieves detailed information about a specific game.
     *
     * @param string $game_id Unique game identifier
     * @return GetGame200Resource|404Resource
     */
    public function getGame(
        string $game_id
    ): GetGame200Resource|404Resource;

    /**
     * List all games
     *
     * Retrieves a paginated list of games with optional filtering.
     *
     * @param int $page Page number for pagination
     * @param int $limit Number of items per page
     * @param \App\Models\GameStatus $status Filter by game status
     * @param string $player_id Filter games by player ID
     * @return ListGames200Resource|400Resource|401Resource
     */
    public function listGames(
        int $page,
        int $limit,
        \App\Models\GameStatus $status,
        string $player_id
    ): ListGames200Resource|400Resource|401Resource;

}
