/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Api;

use App\Models.Leaderboard;
use App\Models.NotFoundError;
use App\Models.PlayerStats;
use App\Http\Resources\GetLeaderboard200Resource;
use App\Http\Resources\GetPlayerStats200Resource|404Resource;

/**
 * StatisticsApiApi
 *
 * Handler interface - implement this to provide business logic
 * Returns Resources with compile-time type safety via union types
 *
 * Operation: getLeaderboard
 * Operation: getPlayerStats
 */
interface StatisticsApiApi
{
    /**
     * Get leaderboard
     *
     * Retrieves the global leaderboard with top players.
     *
     * @param string $timeframe Timeframe for leaderboard statistics
     * @param int $limit Number of top players to return
     * @return GetLeaderboard200Resource
     */
    public function getLeaderboard(
        string $timeframe,
        int $limit
    ): GetLeaderboard200Resource;

    /**
     * Get player statistics
     *
     * Retrieves comprehensive statistics for a player.
     *
     * @param string $player_id Unique player identifier
     * @return GetPlayerStats200Resource|404Resource
     */
    public function getPlayerStats(
        string $player_id
    ): GetPlayerStats200Resource|404Resource;

}
