/**
 * Auto-generated by OpenAPI Generator (https://openapi-generator.tech)
 * OpenAPI spec version: 1.0.0
 *
 * DO NOT EDIT - This file was generated by the laravel-max generator
 */

<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Api\GameplayApiApi;
use Illuminate\Http\JsonResponse;

/**
 * Controller
 *
 * Auto-generated controller for  operation
 * One controller per operation pattern
 *
 * OpenAPI Operation: 
 * HTTP Method:  
 */
class Controller
{
    public function __construct(
        private readonly GameplayApiApi $handler
    ) {}

    /**
     * 
     *
     * @return JsonResponse
     */
    public function __invoke(
    ): JsonResponse
    {
        // Delegate to Handler
        $resource = $this->handler->(
        );

        // Resource enforces HTTP code and headers
        return $resource->response($request);
    }
}
